from django.urls import path
from django.views.generic import TemplateView

from . import (
    alarm_views,
    asset_views,
    backup_views,
    backup_credential_views,
    cisco_backup_views,
    dashboard_views,
    log_views,
    mikrotik_views,
    mikrotik_backup_views,
    backup_storage_views,
    phase77_views,
    phase78_views,
    report_views,
    sfp_views,
    ssh_views,
    topology_views,
    user_views,
)
from .access_control import (
    admin_required,
    backup_management_required,
    cisco_import_required,
    cisco_pull_required,
    operator_or_admin_required,
    refresh_required,
    sfp_poll_required,
    view_required,
)

app_name = "inventory"

from . import backup_health_views
urlpatterns = [
    path('backup-health/', backup_health_views.backup_health_dashboard, name='backup_health_dashboard'),  # PHASE90_BACKUP_HEALTH_UI_URL
    path("dashboard-preview/", view_required(TemplateView.as_view(template_name="inventory/dashboard_visual_preview.html")), name="dashboard_visual_preview"),
    path("", view_required(dashboard_views.switch_list), name="switch_list"),
    path("refresh-all/", refresh_required(dashboard_views.switchmap_refresh_all_data), name="switchmap_refresh_all_data"),
    path("dashboard/data/", view_required(dashboard_views.switchmap_dashboard_data_view), name="switchmap_dashboard_data"),
    path("dashboard/device-browser/", view_required(dashboard_views.dashboard_device_browser_fragment_view), name="dashboard_device_browser_fragment"),  # Phase107R2 lazy dashboard device browser
    path("switch/<int:switch_id>/refresh-step/", refresh_required(dashboard_views.switchmap_refresh_switch_step), name="switch_refresh_step"),
    path("switches/import/", admin_required(dashboard_views.switch_bulk_import), name="switch_bulk_import"),
    path("exports/ports.csv", view_required(dashboard_views.export_ports_csv_view), name="export_ports_csv"),
    path("poll-all/ports/", refresh_required(dashboard_views.poll_all_ports_view), name="poll_all_ports"),
    path("poll-all/discovery/", refresh_required(dashboard_views.poll_all_discovery_view), name="poll_all_discovery"),
    path("topology/", view_required(topology_views.topology_view), name="topology"),
    path("topology/edge/<int:port_id>/", view_required(topology_views.topology_edge_detail_view), name="topology_edge_detail"),
    path("mikrotik/", view_required(mikrotik_views.mikrotik_center_view), name="mikrotik_center"),
    path("mikrotik/data/", view_required(mikrotik_views.mikrotik_center_data_view), name="mikrotik_center_data"),
    path("mikrotik/auto-snmp-poll/", refresh_required(mikrotik_views.mikrotik_auto_snmp_poll_view), name="mikrotik_auto_snmp_poll"),
    path("mikrotik/live-poll/", operator_or_admin_required(mikrotik_views.mikrotik_live_poll_view), name="mikrotik_live_poll"),

    path("noc/", view_required(phase77_views.phase77_noc_dashboard_view), name="phase77_noc_dashboard"),
    path("phase77/status.json", view_required(phase77_views.phase77_status_json_view), name="phase77_status_json"),
    path("automation/templates/", operator_or_admin_required(phase77_views.automation_templates_view), name="automation_templates"),
    path("automation/templates/new/", operator_or_admin_required(phase77_views.automation_template_create_view), name="automation_template_create"),
    path("automation/templates/seed-defaults/", operator_or_admin_required(phase77_views.seed_default_job_templates_view), name="automation_template_seed_defaults"),
    path("automation/templates/<int:template_id>/edit/", operator_or_admin_required(phase77_views.automation_template_edit_view), name="automation_template_edit"),
    path("automation/templates/<int:template_id>/preview/", operator_or_admin_required(phase77_views.automation_template_preview_view), name="automation_template_preview"),
    path("config-backups/", backup_management_required(phase77_views.config_backups_view), name="config_backups"),
    path("config-backups/<int:snapshot_id>/", backup_management_required(phase77_views.config_backup_detail_view), name="config_backup_detail"),
    path("config-backups/<int:snapshot_id>/download/", backup_management_required(phase77_views.config_backup_download_view), name="config_backup_download"),
    path("assets/completion/", view_required(phase77_views.asset_completion_view), name="asset_completion"),
    path("assets/", view_required(asset_views.asset_documentation_view), name="asset_documentation"),
    path("assets/export.csv", view_required(asset_views.asset_documentation_export_csv_view), name="asset_documentation_export_csv"),
    path("assets/export.xlsx", view_required(asset_views.asset_documentation_export_xlsx_view), name="asset_documentation_export_xlsx"),
    path("reports/", view_required(report_views.reports_view), name="reports"),
    path("logs/", view_required(log_views.action_logs_view), name="action_logs"),
    path("logs/export.csv", view_required(log_views.action_logs_export_csv_view), name="action_logs_export_csv"),
    path("logs/cisco/import/", cisco_import_required(log_views.cisco_syslog_import_view), name="cisco_syslog_import"),
    path("logs/cisco/pull/", cisco_pull_required(log_views.cisco_syslog_pull_view), name="cisco_syslog_pull"),
    path("logs/cisco/export.csv", view_required(log_views.cisco_syslog_export_csv_view), name="cisco_syslog_export_csv"),
    path("users/", admin_required(user_views.user_management_view), name="user_management"),
    path("users/new/", admin_required(user_views.user_create_view), name="user_create"),
    path("users/<int:user_id>/edit/", admin_required(user_views.user_edit_view), name="user_edit"),
    path("users/<int:user_id>/password/", admin_required(user_views.user_password_view), name="user_password"),
    path("cisco-backups/", backup_management_required(cisco_backup_views.cisco_backup_center_view), name="cisco_backup_center"),
    path("cisco-backups/run/", backup_management_required(cisco_backup_views.cisco_backup_run_view), name="cisco_backup_run"),
    path("cisco-backups/batch/", backup_management_required(cisco_backup_views.cisco_backup_batch_view), name="cisco_backup_batch"),
    path("cisco-backups/<str:backup_id>/", backup_management_required(cisco_backup_views.cisco_backup_detail_view), name="cisco_backup_detail"),
    path("cisco-backups/<str:backup_id>/download/", backup_management_required(cisco_backup_views.cisco_backup_download_view), name="cisco_backup_download"),
    path("cisco-backups/<str:backup_id>/validate-restore/", admin_required(cisco_backup_views.cisco_backup_validate_restore_view), name="cisco_backup_validate_restore"),
    path("backup-credentials/", backup_management_required(backup_credential_views.backup_credential_prepare_view), name="backup_credential_prepare"),
    path("backup-storage/", backup_management_required(backup_storage_views.backup_storage_status_view), name="backup_storage_status"),
    path("mikrotik-backups/", backup_management_required(mikrotik_backup_views.mikrotik_backup_center_view), name="mikrotik_backup_center"),
    path("mikrotik-backups/run/", backup_management_required(mikrotik_backup_views.mikrotik_backup_run_view), name="mikrotik_backup_run"),
    path("mikrotik-backups/batch/", backup_management_required(mikrotik_backup_views.mikrotik_backup_batch_view), name="mikrotik_backup_batch"),
    path("mikrotik-backups/<str:backup_id>/download/", admin_required(mikrotik_backup_views.mikrotik_backup_download_view), name="mikrotik_backup_download"),
    path("mikrotik-backups/<str:backup_id>/validate-restore/", admin_required(mikrotik_backup_views.mikrotik_backup_validate_restore_view), name="mikrotik_backup_validate_restore"),
    path("mikrotik-backups/<str:backup_id>/", backup_management_required(mikrotik_backup_views.mikrotik_backup_detail_view), name="mikrotik_backup_detail"),
    path("backups/", backup_management_required(backup_views.backup_center_view), name="backup_center"),
    path("backups/create/", backup_management_required(backup_views.backup_create_view), name="backup_create"),
    path("backups/download/<str:filename>/", backup_management_required(backup_views.backup_download_view), name="backup_download"),
    path("backups/validate-restore/", backup_management_required(backup_views.backup_validate_restore_view), name="backup_validate_restore"),
    path("alarms/", view_required(alarm_views.alarm_center_view), name="alarm_center"),
    path("alarms/rules/", view_required(alarm_views.alarm_rules_view), name="alarm_rules"),
    path("alarms/cleanup/", view_required(phase78_views.phase78_alarm_cleanup_view), name="phase78_alarm_cleanup"),
    path("alarms/cleanup/recheck/", operator_or_admin_required(phase78_views.phase78_alarm_recheck_view), name="phase78_alarm_recheck"),
    path("alarms/cleanup/resolve-stale/", operator_or_admin_required(phase78_views.phase78_alarm_resolve_stale_view), name="phase78_alarm_resolve_stale"),
    path("phase78/alarm-cleanup/status.json", view_required(phase78_views.phase78_alarm_cleanup_status_json), name="phase78_alarm_cleanup_status_json"),
    path("alarms/sync/", operator_or_admin_required(alarm_views.alarm_sync_view), name="alarm_sync"),
    path("alarms/bulk-action/", operator_or_admin_required(alarm_views.alarm_bulk_action_view), name="alarm_bulk_action"),
    path("alarms/<int:alarm_id>/", view_required(alarm_views.alarm_detail_view), name="alarm_detail"),
    path("alarms/<int:alarm_id>/ack/", operator_or_admin_required(alarm_views.alarm_acknowledge_view), name="alarm_acknowledge"),
    path("alarms/<int:alarm_id>/resolve/", operator_or_admin_required(alarm_views.alarm_resolve_view), name="alarm_resolve"),
    path("sfp-monitor/", view_required(sfp_views.sfp_monitor_view), name="sfp_monitor"),
    path("sfp-monitor/poll/", sfp_poll_required(sfp_views.sfp_monitor_poll_view), name="sfp_monitor_poll"),
    path("sfp-monitor/data/", view_required(sfp_views.sfp_monitor_data_view), name="sfp_monitor_data"),
    path("switch/<int:switch_id>/edit/", admin_required(dashboard_views.switch_edit), name="switch_edit"),
    path("switch/<int:switch_id>/", view_required(dashboard_views.switch_detail), name="switch_detail"),
    path("switch/<int:switch_id>/snmp-test/", refresh_required(dashboard_views.switch_snmp_test), name="switch_snmp_test"),
    path("switch/<int:switch_id>/poll-now/", refresh_required(dashboard_views.switch_poll_now), name="switch_poll_now"),
    path("switch/<int:switch_id>/discovery-now/", refresh_required(dashboard_views.switch_discovery_now), name="switch_discovery_now"),
    path("switch/<int:switch_id>/sync-snmp-ports/", refresh_required(dashboard_views.switch_sync_snmp_ports), name="switch_sync_snmp_ports"),
    path("switch/<int:switch_id>/ports/", view_required(dashboard_views.switch_ports_table), name="switch_ports_table"),
    path("switch/<int:switch_id>/bulk-ssh-action/", operator_or_admin_required(ssh_views.switch_bulk_ssh_action), name="switch_bulk_ssh_action"),
    path("port-action/", operator_or_admin_required(ssh_views.port_ssh_action), name="port_ssh_action"),
    path("port-action", operator_or_admin_required(ssh_views.port_ssh_action), name="port_ssh_action_no_slash"),
    path("ssh-action/", operator_or_admin_required(ssh_views.port_ssh_action), name="ssh_action_root"),
    path("ssh-action", operator_or_admin_required(ssh_views.port_ssh_action), name="ssh_action_root_no_slash"),
    path("ssh-port-action/", operator_or_admin_required(ssh_views.switchmap_ajax_ssh_port_action), name="switchmap_ajax_ssh_port_action"),
    path("ssh-port-multi-action/", operator_or_admin_required(ssh_views.switchmap_ajax_multi_ssh_port_action), name="switchmap_ajax_multi_ssh_port_action"),
    path("ssh-port-preview/", operator_or_admin_required(ssh_views.ssh_action_preview), name="ssh_action_preview"),
    path("switch/<int:switch_id>/port-action/", operator_or_admin_required(ssh_views.port_ssh_action), name="switch_port_ssh_action"),
    path("switch/<int:switch_id>/port-action", operator_or_admin_required(ssh_views.port_ssh_action), name="switch_port_ssh_action_no_slash"),
    path("switch/<int:switch_id>/ssh-action/", operator_or_admin_required(ssh_views.port_ssh_action), name="switch_ssh_action_root"),
    path("port/<int:port_id>/payload/", view_required(dashboard_views.port_payload_json), name="port_payload_json"),
    path("port/<int:port_id>/ssh/", operator_or_admin_required(dashboard_views.port_ssh_helper), name="port_ssh_helper"),
    path("port/<int:port_id>/history/", view_required(asset_views.port_documentation_history_view), name="port_documentation_history"),
    path("port/<int:port_id>/edit/", operator_or_admin_required(dashboard_views.port_edit), name="port_edit"),
]
