# Generated by Django 5.2.15 on 2026-06-20 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('management_ip', models.GenericIPAddressField(unique=True)),
                ('model', models.CharField(default='Cisco Catalyst 3850', max_length=100)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('port_count', models.PositiveSmallIntegerField(default=48)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(max_length=30)),
                ('display_order', models.PositiveSmallIntegerField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('connected_device', models.CharField(blank=True, max_length=150)),
                ('vlan', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('disabled', 'Disabled'), ('error', 'Error')], default='down', max_length=20)),
                ('poe_enabled', models.BooleanField(default=False)),
                ('room', models.CharField(blank=True, max_length=100)),
                ('patch_panel', models.CharField(blank=True, max_length=100)),
                ('outlet', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='inventory.switch')),
            ],
            options={
                'ordering': ['switch', 'display_order'],
                'constraints': [models.UniqueConstraint(fields=('switch', 'interface_name'), name='unique_switch_interface')],
            },
        ),
    ]
