# Generated by SwitchMap Phase 36 - Asset / Documentation

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_system_audit_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="port",
            name="rack",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="port",
            name="rack_unit",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="port",
            name="patch_panel_port",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="port",
            name="cable_type",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="port",
            name="cable_length",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="port",
            name="asset_tag",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="port",
            name="documentation_status",
            field=models.CharField(
                choices=[
                    ("undocumented", "Undocumented"),
                    ("partial", "Partial"),
                    ("documented", "Documented"),
                    ("needs_review", "Needs Review"),
                ],
                default="undocumented",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="PortDocumentationHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("interface_name", models.CharField(max_length=80)),
                ("changed_fields", models.CharField(blank=True, max_length=500)),
                ("before_data", models.TextField(blank=True)),
                ("after_data", models.TextField(blank=True)),
                ("actor_username", models.CharField(blank=True, max_length=150)),
                ("actor_role", models.CharField(blank=True, max_length=50)),
                ("client_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("request_path", models.CharField(blank=True, max_length=255)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("port", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="documentation_history", to="inventory.port")),
                ("switch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="port_documentation_history", to="inventory.switch")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["port", "-created_at"], name="pdh_port_created_idx"),
                    models.Index(fields=["switch", "-created_at"], name="pdh_switch_created_idx"),
                    models.Index(fields=["actor_username", "-created_at"], name="pdh_actor_created_idx"),
                ],
            },
        ),
    ]
