# Generated by SwitchMap Phase 55 - MikroTik Data Model Foundation

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_phase40_device_classification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("kind", models.CharField(choices=[("hq", "HQ"), ("remote", "Remote"), ("home", "Home"), ("cloud", "Cloud"), ("wireless", "Wireless"), ("unknown", "Unknown")], default="unknown", max_length=30)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["kind", "name"],
            },
        ),
        migrations.CreateModel(
            name="RouterHealthSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(choices=[("up", "Up"), ("warning", "Warning"), ("down", "Down"), ("unknown", "Unknown")], default="unknown", max_length=20)),
                ("source", models.CharField(choices=[("snmp", "SNMP"), ("ssh", "SSH"), ("api", "RouterOS API"), ("manual", "Manual"), ("system", "System")], default="system", max_length=30)),
                ("cpu_load", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("memory_free_mb", models.PositiveIntegerField(blank=True, null=True)),
                ("uptime", models.CharField(blank=True, max_length=100)),
                ("routeros_version", models.CharField(blank=True, max_length=100)),
                ("public_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("tunnel_count", models.PositiveSmallIntegerField(default=0)),
                ("active_tunnel_count", models.PositiveSmallIntegerField(default=0)),
                ("raw_summary", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("switch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="router_health_snapshots", to="inventory.switch")),
            ],
            options={
                "ordering": ["-collected_at"],
                "indexes": [
                    models.Index(fields=["switch", "-collected_at"], name="rhs_switch_collected_idx"),
                    models.Index(fields=["status", "-collected_at"], name="rhs_status_collected_idx"),
                    models.Index(fields=["source", "-collected_at"], name="rhs_source_collected_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WanLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                ("link_type", models.CharField(choices=[("starlink", "Starlink"), ("fiber", "Fiber"), ("sim", "SIM"), ("vps", "VPS"), ("local_transit", "Local Transit"), ("other", "Other")], default="other", max_length=30)),
                ("provider", models.CharField(blank=True, max_length=120)),
                ("interface_name", models.CharField(blank=True, max_length=80)),
                ("public_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("local_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("purpose", models.CharField(blank=True, max_length=180)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("site", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wan_links", to="inventory.site")),
                ("switch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wan_links", to="inventory.switch")),
            ],
            options={
                "ordering": ["site__name", "switch__name", "name"],
                "indexes": [
                    models.Index(fields=["switch", "is_active"], name="wan_switch_active_idx"),
                    models.Index(fields=["site", "is_active"], name="wan_site_active_idx"),
                    models.Index(fields=["link_type", "is_active"], name="wan_type_active_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RouterTunnel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=140, unique=True)),
                ("tunnel_type", models.CharField(choices=[("wireguard", "WireGuard"), ("l2tp_ipsec", "L2TP/IPsec"), ("eoip", "EoIP"), ("gre", "GRE"), ("ovpn", "OpenVPN"), ("vpn_endpoint", "VPN Endpoint"), ("local_transit", "Local Transit"), ("cap_management", "CAP Management"), ("unknown", "Unknown")], default="unknown", max_length=30)),
                ("local_tunnel_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("remote_tunnel_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("routed_networks", models.CharField(blank=True, max_length=255)),
                ("failover_priority", models.PositiveSmallIntegerField(default=1)),
                ("status", models.CharField(choices=[("up", "Up"), ("down", "Down"), ("warning", "Warning"), ("unknown", "Unknown")], default="unknown", max_length=20)),
                ("confidence", models.CharField(choices=[("documented", "Documented"), ("inferred", "Inferred"), ("needs_review", "Needs Review")], default="inferred", max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("destination_site", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inbound_router_tunnels", to="inventory.site")),
                ("destination_switch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inbound_router_tunnels", to="inventory.switch")),
                ("source_site", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="outbound_router_tunnels", to="inventory.site")),
                ("source_switch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="outbound_router_tunnels", to="inventory.switch")),
            ],
            options={
                "ordering": ["failover_priority", "name"],
                "indexes": [
                    models.Index(fields=["source_switch", "is_active"], name="rt_src_switch_active_idx"),
                    models.Index(fields=["destination_switch", "is_active"], name="rt_dst_switch_active_idx"),
                    models.Index(fields=["tunnel_type", "status"], name="rt_type_status_idx"),
                    models.Index(fields=["confidence", "is_active"], name="rt_conf_active_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RoutingPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=140, unique=True)),
                ("policy_type", models.CharField(choices=[("iran", "Iran Traffic"), ("foreign", "Foreign Traffic"), ("site_to_site", "Site-to-Site"), ("management", "Management"), ("backup", "Backup / Failover"), ("dns", "DNS / Split DNS"), ("other", "Other")], default="other", max_length=30)),
                ("source_zone", models.CharField(blank=True, max_length=120)),
                ("destination_zone", models.CharField(blank=True, max_length=120)),
                ("preferred_path", models.CharField(blank=True, max_length=180)),
                ("backup_path", models.CharField(blank=True, max_length=180)),
                ("routing_table", models.CharField(blank=True, max_length=100)),
                ("address_list", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                ("confidence", models.CharField(choices=[("documented", "Documented"), ("inferred", "Inferred"), ("needs_review", "Needs Review")], default="inferred", max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("site", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="routing_policies", to="inventory.site")),
                ("switch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="routing_policies", to="inventory.switch")),
            ],
            options={
                "ordering": ["site__name", "switch__name", "policy_type", "name"],
                "indexes": [
                    models.Index(fields=["switch", "is_active"], name="rp_switch_active_idx"),
                    models.Index(fields=["site", "is_active"], name="rp_site_active_idx"),
                    models.Index(fields=["policy_type", "is_active"], name="rp_type_active_idx"),
                ],
            },
        ),
    ]
