# Generated by SwitchMap Phase79.1
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0018_phase77_indexes_and_operational_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortConnectionHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("interface_name", models.CharField(max_length=80)),
                ("event_type", models.CharField(choices=[("seen", "Seen"), ("up", "Up"), ("down", "Down"), ("change", "Change"), ("manual", "Manual")], default="seen", max_length=20)),
                ("status_before", models.CharField(blank=True, max_length=30)),
                ("status_after", models.CharField(blank=True, max_length=30)),
                ("observed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("occurrence_count", models.PositiveIntegerField(default=1)),
                ("neighbor_source", models.CharField(blank=True, max_length=30)),
                ("neighbor_device", models.CharField(blank=True, max_length=200)),
                ("neighbor_port", models.CharField(blank=True, max_length=200)),
                ("neighbor_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("connected_device", models.CharField(blank=True, max_length=150)),
                ("device_type", models.CharField(blank=True, max_length=30)),
                ("owner", models.CharField(blank=True, max_length=150)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("mac_address", models.CharField(blank=True, max_length=32)),
                ("mac_addresses", models.TextField(blank=True)),
                ("mac_count", models.PositiveSmallIntegerField(default=0)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("snmp_alias", models.CharField(blank=True, max_length=200)),
                ("vlan", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("port_mode", models.CharField(blank=True, max_length=20)),
                ("access_vlan", models.PositiveIntegerField(blank=True, null=True)),
                ("native_vlan", models.PositiveIntegerField(blank=True, null=True)),
                ("voice_vlan", models.PositiveIntegerField(blank=True, null=True)),
                ("trunk_vlans", models.CharField(blank=True, max_length=255)),
                ("source", models.CharField(blank=True, max_length=80)),
                ("note", models.TextField(blank=True)),
                ("identity_hash", models.CharField(blank=True, max_length=64)),
                ("port", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="connection_history", to="inventory.port")),
                ("switch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="port_connection_history", to="inventory.switch")),
            ],
            options={
                "ordering": ["-observed_at", "-id"],
                "indexes": [
                    models.Index(fields=["port", "-observed_at"], name="pch_port_obs_idx"),
                    models.Index(fields=["switch", "-observed_at"], name="pch_sw_obs_idx"),
                    models.Index(fields=["event_type", "-observed_at"], name="pch_event_obs_idx"),
                    models.Index(fields=["status_after", "-observed_at"], name="pch_status_obs_idx"),
                    models.Index(fields=["port", "identity_hash"], name="pch_port_hash_idx"),
                ],
            },
        ),
    ]
