from __future__ import annotations

import re
import shutil
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BACKUP_DIR = ROOT / "backups" / f"phase79_1_port_history_{datetime.now().strftime('%Y%m%d_%H%M%S')}"

MODELS = ROOT / "inventory" / "models.py"
SNMP_TOOLS = ROOT / "inventory" / "snmp_tools.py"
MIGRATION = ROOT / "inventory" / "migrations" / "0019_phase79_port_connection_history.py"
HISTORY_MODULE = ROOT / "inventory" / "phase79_history.py"
COMMAND = ROOT / "inventory" / "management" / "commands" / "phase79_capture_port_history.py"

MODEL_BLOCK = r'''

class PortConnectionHistory(models.Model):
    class EventType(models.TextChoices):
        SEEN = "seen", "Seen"
        UP = "up", "Up"
        DOWN = "down", "Down"
        CHANGE = "change", "Change"
        MANUAL = "manual", "Manual"

    port = models.ForeignKey(
        Port,
        on_delete=models.CASCADE,
        related_name="connection_history",
    )
    switch = models.ForeignKey(
        Switch,
        on_delete=models.CASCADE,
        related_name="port_connection_history",
    )
    interface_name = models.CharField(max_length=80)
    event_type = models.CharField(max_length=20, choices=EventType.choices, default=EventType.SEEN)
    status_before = models.CharField(max_length=30, blank=True)
    status_after = models.CharField(max_length=30, blank=True)
    observed_at = models.DateTimeField(default=timezone.now)
    last_verified_at = models.DateTimeField(null=True, blank=True)
    occurrence_count = models.PositiveIntegerField(default=1)

    neighbor_source = models.CharField(max_length=30, blank=True)
    neighbor_device = models.CharField(max_length=200, blank=True)
    neighbor_port = models.CharField(max_length=200, blank=True)
    neighbor_ip = models.GenericIPAddressField(null=True, blank=True)
    connected_device = models.CharField(max_length=150, blank=True)
    device_type = models.CharField(max_length=30, blank=True)
    owner = models.CharField(max_length=150, blank=True)
    ip_address = models.GenericIPAddressField(null=True, blank=True)
    mac_address = models.CharField(max_length=32, blank=True)
    mac_addresses = models.TextField(blank=True)
    mac_count = models.PositiveSmallIntegerField(default=0)

    description = models.CharField(max_length=200, blank=True)
    snmp_alias = models.CharField(max_length=200, blank=True)
    vlan = models.PositiveSmallIntegerField(null=True, blank=True)
    port_mode = models.CharField(max_length=20, blank=True)
    access_vlan = models.PositiveIntegerField(null=True, blank=True)
    native_vlan = models.PositiveIntegerField(null=True, blank=True)
    voice_vlan = models.PositiveIntegerField(null=True, blank=True)
    trunk_vlans = models.CharField(max_length=255, blank=True)

    source = models.CharField(max_length=80, blank=True)
    note = models.TextField(blank=True)
    identity_hash = models.CharField(max_length=64, blank=True)

    class Meta:
        ordering = ["-observed_at", "-id"]
        indexes = [
            models.Index(fields=["port", "-observed_at"], name="pch_port_obs_idx"),
            models.Index(fields=["switch", "-observed_at"], name="pch_sw_obs_idx"),
            models.Index(fields=["event_type", "-observed_at"], name="pch_event_obs_idx"),
            models.Index(fields=["status_after", "-observed_at"], name="pch_status_obs_idx"),
            models.Index(fields=["port", "identity_hash"], name="pch_port_hash_idx"),
        ]

    def identity_label(self):
        if self.connected_device:
            return self.connected_device
        if self.neighbor_device:
            return self.neighbor_device
        if self.mac_address:
            return self.mac_address
        if self.mac_addresses:
            return self.mac_addresses.splitlines()[0]
        return "-"

    def __str__(self):
        return f"{self.switch.name} {self.interface_name} {self.event_type}"
'''

MIGRATION_TEXT = r'''# Generated by SwitchMap Phase79.1
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0018_phase77_indexes_and_operational_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortConnectionHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("interface_name", models.CharField(max_length=80)),
                ("event_type", models.CharField(choices=[("seen", "Seen"), ("up", "Up"), ("down", "Down"), ("change", "Change"), ("manual", "Manual")], default="seen", max_length=20)),
                ("status_before", models.CharField(blank=True, max_length=30)),
                ("status_after", models.CharField(blank=True, max_length=30)),
                ("observed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("occurrence_count", models.PositiveIntegerField(default=1)),
                ("neighbor_source", models.CharField(blank=True, max_length=30)),
                ("neighbor_device", models.CharField(blank=True, max_length=200)),
                ("neighbor_port", models.CharField(blank=True, max_length=200)),
                ("neighbor_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("connected_device", models.CharField(blank=True, max_length=150)),
                ("device_type", models.CharField(blank=True, max_length=30)),
                ("owner", models.CharField(blank=True, max_length=150)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("mac_address", models.CharField(blank=True, max_length=32)),
                ("mac_addresses", models.TextField(blank=True)),
                ("mac_count", models.PositiveSmallIntegerField(default=0)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("snmp_alias", models.CharField(blank=True, max_length=200)),
                ("vlan", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("port_mode", models.CharField(blank=True, max_length=20)),
                ("access_vlan", models.PositiveIntegerField(blank=True, null=True)),
                ("native_vlan", models.PositiveIntegerField(blank=True, null=True)),
                ("voice_vlan", models.PositiveIntegerField(blank=True, null=True)),
                ("trunk_vlans", models.CharField(blank=True, max_length=255)),
                ("source", models.CharField(blank=True, max_length=80)),
                ("note", models.TextField(blank=True)),
                ("identity_hash", models.CharField(blank=True, max_length=64)),
                ("port", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="connection_history", to="inventory.port")),
                ("switch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="port_connection_history", to="inventory.switch")),
            ],
            options={
                "ordering": ["-observed_at", "-id"],
                "indexes": [
                    models.Index(fields=["port", "-observed_at"], name="pch_port_obs_idx"),
                    models.Index(fields=["switch", "-observed_at"], name="pch_sw_obs_idx"),
                    models.Index(fields=["event_type", "-observed_at"], name="pch_event_obs_idx"),
                    models.Index(fields=["status_after", "-observed_at"], name="pch_status_obs_idx"),
                    models.Index(fields=["port", "identity_hash"], name="pch_port_hash_idx"),
                ],
            },
        ),
    ]
'''

HISTORY_TEXT = r'''from __future__ import annotations

import hashlib
from typing import Optional

from django.utils import timezone

from .models import Port, PortConnectionHistory

IDENTITY_FIELDS = (
    "connected_device",
    "neighbor_source",
    "neighbor_device",
    "neighbor_port",
    "neighbor_ip",
    "ip_address",
    "mac_address",
    "mac_addresses",
    "mac_count",
    "device_type",
    "owner",
)


def _clean(value):
    if value is None:
        return ""
    return str(value).strip()


def port_has_identity_data(port: Port) -> bool:
    return any(_clean(getattr(port, field, "")) for field in IDENTITY_FIELDS if field != "mac_count") or int(getattr(port, "mac_count", 0) or 0) > 0


def port_identity_hash(port: Port) -> str:
    parts = []
    for field in IDENTITY_FIELDS:
        parts.append(f"{field}={_clean(getattr(port, field, ''))}")
    parts.extend([
        f"vlan={_clean(port.access_vlan or port.vlan)}",
        f"mode={_clean(port.port_mode)}",
    ])
    raw = "|".join(parts)
    return hashlib.sha256(raw.encode("utf-8", errors="ignore")).hexdigest()


def _history_kwargs(port: Port, *, event_type: str, source: str, observed_at, previous_status: str = "", note: str = "") -> dict:
    return {
        "port": port,
        "switch": port.switch,
        "interface_name": port.interface_name,
        "event_type": event_type,
        "status_before": previous_status or "",
        "status_after": port.status or "",
        "observed_at": observed_at or timezone.now(),
        "last_verified_at": observed_at or timezone.now(),
        "neighbor_source": port.neighbor_source or "",
        "neighbor_device": port.neighbor_device or "",
        "neighbor_port": port.neighbor_port or "",
        "neighbor_ip": port.neighbor_ip,
        "connected_device": port.connected_device or "",
        "device_type": port.device_type or "",
        "owner": port.owner or "",
        "ip_address": port.ip_address,
        "mac_address": port.mac_address or "",
        "mac_addresses": port.mac_addresses or "",
        "mac_count": int(port.mac_count or 0),
        "description": port.description or "",
        "snmp_alias": port.snmp_alias or "",
        "vlan": port.vlan,
        "port_mode": port.port_mode or "",
        "access_vlan": port.access_vlan,
        "native_vlan": port.native_vlan,
        "voice_vlan": port.voice_vlan,
        "trunk_vlans": port.trunk_vlans or "",
        "source": source or "",
        "note": note or "",
        "identity_hash": port_identity_hash(port),
    }


def record_port_identity_snapshot(port: Port, *, source: str = "discovery", observed_at=None, force: bool = False, note: str = "") -> Optional[PortConnectionHistory]:
    if not force and not port_has_identity_data(port):
        return None

    observed_at = observed_at or timezone.now()
    identity_hash = port_identity_hash(port)
    latest = PortConnectionHistory.objects.filter(port=port).order_by("-observed_at", "-id").first()

    if latest and latest.event_type == PortConnectionHistory.EventType.SEEN and latest.identity_hash == identity_hash:
        latest.last_verified_at = observed_at
        latest.occurrence_count = int(latest.occurrence_count or 0) + 1
        latest.status_after = port.status or ""
        latest.save(update_fields=["last_verified_at", "occurrence_count", "status_after"])
        return latest

    return PortConnectionHistory.objects.create(**_history_kwargs(
        port,
        event_type=PortConnectionHistory.EventType.SEEN,
        source=source,
        observed_at=observed_at,
        note=note,
    ))


def record_port_connection_event(port: Port, *, event_type: str, source: str = "snmp_status", observed_at=None, previous_status: str = "", note: str = "") -> Optional[PortConnectionHistory]:
    if not port_has_identity_data(port):
        latest_identity = PortConnectionHistory.objects.filter(port=port).exclude(identity_hash="").order_by("-observed_at", "-id").first()
        if latest_identity:
            return PortConnectionHistory.objects.create(
                port=port,
                switch=port.switch,
                interface_name=port.interface_name,
                event_type=event_type,
                status_before=previous_status or "",
                status_after=port.status or "",
                observed_at=observed_at or timezone.now(),
                last_verified_at=observed_at or timezone.now(),
                neighbor_source=latest_identity.neighbor_source,
                neighbor_device=latest_identity.neighbor_device,
                neighbor_port=latest_identity.neighbor_port,
                neighbor_ip=latest_identity.neighbor_ip,
                connected_device=latest_identity.connected_device,
                device_type=latest_identity.device_type,
                owner=latest_identity.owner,
                ip_address=latest_identity.ip_address,
                mac_address=latest_identity.mac_address,
                mac_addresses=latest_identity.mac_addresses,
                mac_count=latest_identity.mac_count,
                description=latest_identity.description,
                snmp_alias=latest_identity.snmp_alias,
                vlan=latest_identity.vlan,
                port_mode=latest_identity.port_mode,
                access_vlan=latest_identity.access_vlan,
                native_vlan=latest_identity.native_vlan,
                voice_vlan=latest_identity.voice_vlan,
                trunk_vlans=latest_identity.trunk_vlans,
                source=source or "",
                note=note or "copied from latest identity snapshot",
                identity_hash=latest_identity.identity_hash,
            )
        return None

    return PortConnectionHistory.objects.create(**_history_kwargs(
        port,
        event_type=event_type,
        source=source,
        observed_at=observed_at or timezone.now(),
        previous_status=previous_status,
        note=note,
    ))


def latest_port_connection(port: Port) -> Optional[PortConnectionHistory]:
    return PortConnectionHistory.objects.filter(port=port).exclude(identity_hash="").order_by("-observed_at", "-id").first()
'''

COMMAND_TEXT = r'''from django.core.management.base import BaseCommand
from django.utils import timezone

from inventory.models import Port, PortConnectionHistory, Switch
from inventory.phase79_history import record_port_identity_snapshot


class Command(BaseCommand):
    help = "Capture current Port identity data into Phase79 PortConnectionHistory. No network polling is performed."

    def add_arguments(self, parser):
        parser.add_argument("--switch", dest="switch", default="", help="Switch name or management IP")
        parser.add_argument("--source", dest="source", default="manual_capture", help="History source label")
        parser.add_argument("--force", action="store_true", help="Create records even when no identity data exists")
        parser.add_argument("--dry-run", action="store_true", help="Show counts without writing")

    def handle(self, *args, **options):
        qs = Port.objects.select_related("switch").order_by("switch__name", "display_order")
        switch_filter = str(options.get("switch") or "").strip()
        if switch_filter:
            switch = Switch.objects.filter(name__iexact=switch_filter).first() or Switch.objects.filter(management_ip=switch_filter).first()
            if not switch:
                self.stdout.write(f"PHASE79_1_CAPTURE_FAIL switch_not_found={switch_filter}")
                return
            qs = qs.filter(switch=switch)

        total = qs.count()
        with_identity = 0
        touched = 0
        created_or_updated = 0
        dry_run = bool(options.get("dry_run"))
        now = timezone.now()

        for port in qs:
            has_identity = any([
                port.connected_device,
                port.neighbor_device,
                port.neighbor_port,
                port.neighbor_ip,
                port.ip_address,
                port.mac_address,
                port.mac_addresses,
                port.mac_count,
            ])
            if has_identity:
                with_identity += 1
            if dry_run:
                continue
            history = record_port_identity_snapshot(
                port,
                source=str(options.get("source") or "manual_capture"),
                observed_at=now,
                force=bool(options.get("force")),
            )
            touched += 1
            if history:
                created_or_updated += 1

        self.stdout.write("PHASE79_1_CAPTURE_REPORT")
        self.stdout.write(f"total_ports={total}")
        self.stdout.write(f"ports_with_identity={with_identity}")
        self.stdout.write(f"dry_run={1 if dry_run else 0}")
        self.stdout.write(f"processed={touched}")
        self.stdout.write(f"history_rows_now={PortConnectionHistory.objects.count() if not dry_run else 'not_changed'}")
        self.stdout.write(f"created_or_updated={created_or_updated if not dry_run else 'not_changed'}")
        self.stdout.write("PHASE79_1_CAPTURE_OK")
'''

VERIFY_TEXT = r'''from __future__ import annotations

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")

import django
from django.core.management import call_command
from django.db import connection

ok = []
warn = []
fail = []

try:
    django.setup()
    call_command("check", verbosity=0)
    ok.append("django_check: OK")
except Exception as exc:
    fail.append(f"django_setup: {exc}")

if not fail:
    try:
        from inventory.models import Port, PortConnectionHistory
        from inventory.phase79_history import latest_port_connection, record_port_identity_snapshot
        ok.append("model:PortConnectionHistory: OK")
        ok.append("helper:phase79_history: OK")

        tables = set(connection.introspection.table_names())
        if "inventory_portconnectionhistory" in tables:
            ok.append("table:inventory_portconnectionhistory: OK")
        else:
            fail.append("table:inventory_portconnectionhistory missing; run migrate")

        port_count = Port.objects.count()
        history_count = PortConnectionHistory.objects.count() if "inventory_portconnectionhistory" in tables else 0
        identity_ports = Port.objects.exclude(neighbor_device="").count() + Port.objects.exclude(mac_addresses="").count() + Port.objects.exclude(mac_address="").count() + Port.objects.exclude(connected_device="").count()
        ok.append(f"data:ports:{port_count}")
        ok.append(f"data:connection_history_rows:{history_count}")
        if history_count == 0:
            warn.append("phase79:connection_history_empty: no last-device data captured yet")
        if identity_ports == 0:
            warn.append("phase79:current_identity_source_empty: no current neighbor/mac/device data in Port table")
    except Exception as exc:
        fail.append(f"phase79_1_checks: {exc}")

print("PHASE79_1_PORT_HISTORY_REPORT")
print(f"OK_COUNT={len(ok)}")
print(f"WARNING_COUNT={len(warn)}")
print(f"FAIL_COUNT={len(fail)}")
print("\n[OK]")
for item in ok:
    print("OK " + item)
print("\n[WARNING]")
for item in warn:
    print("WARNING " + item)
if not warn:
    print("- none")
print("\n[FAIL]")
for item in fail:
    print("FAIL " + item)
if not fail:
    print("- none")
print("PHASE79_1_VERIFY_" + ("OK" if not fail else "FAIL"))
sys.exit(0 if not fail else 1)
'''


def backup_file(path: Path):
    if not path.exists():
        return
    target = BACKUP_DIR / path.relative_to(ROOT)
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(path, target)


def patch_models():
    text = MODELS.read_text(encoding="utf-8")
    if "from django.utils import timezone" not in text:
        text = text.replace("from django.db import models\n", "from django.db import models\nfrom django.utils import timezone\n", 1)
    if "class PortConnectionHistory(models.Model):" not in text:
        marker = "class CiscoSyslogEntry(models.Model):"
        if marker not in text:
            raise RuntimeError("models.py marker not found: CiscoSyslogEntry")
        text = text.replace(marker, MODEL_BLOCK + "\n" + marker, 1)
    MODELS.write_text(text, encoding="utf-8")


def patch_snmp_tools():
    text = SNMP_TOOLS.read_text(encoding="utf-8")
    if "from inventory.phase79_history import" not in text:
        text = text.replace(
            "from inventory.models import Port\n",
            "from inventory.models import Port\nfrom inventory.phase79_history import record_port_connection_event, record_port_identity_snapshot\n",
            1,
        )

    if "phase79_old_status = port.status" not in text:
        text = text.replace(
            "        if dry_run:\n            continue\n\n        port.snmp_if_index = if_index\n",
            "        if dry_run:\n            continue\n\n        phase79_old_status = port.status\n\n        port.snmp_if_index = if_index\n",
            1,
        )

    if "record_port_connection_event(port, event_type=\"down\"" not in text:
        text = text.replace(
            "        port.save(\n            update_fields=[\n                \"snmp_if_index\",\n                \"snmp_raw_name\",\n                \"snmp_alias\",\n                \"snmp_admin_status\",\n                \"snmp_oper_status\",\n                \"snmp_speed_mbps\",\n                \"snmp_last_poll\",\n                \"status\",\n                \"port_mode\",\n                \"access_vlan\",\n                \"native_vlan\",\n                \"voice_vlan\",\n                \"trunk_vlans\",\n                \"vlan\",\n                \"poe_enabled\",\n                \"poe_admin_status\",\n                \"poe_detection_status\",\n                \"updated_at\",\n            ]\n        )\n        updated_count += 1\n",
            "        port.save(\n            update_fields=[\n                \"snmp_if_index\",\n                \"snmp_raw_name\",\n                \"snmp_alias\",\n                \"snmp_admin_status\",\n                \"snmp_oper_status\",\n                \"snmp_speed_mbps\",\n                \"snmp_last_poll\",\n                \"status\",\n                \"port_mode\",\n                \"access_vlan\",\n                \"native_vlan\",\n                \"voice_vlan\",\n                \"trunk_vlans\",\n                \"vlan\",\n                \"poe_enabled\",\n                \"poe_admin_status\",\n                \"poe_detection_status\",\n                \"updated_at\",\n            ]\n        )\n        try:\n            if phase79_old_status != new_status:\n                if phase79_old_status == Port.Status.UP and new_status != Port.Status.UP:\n                    record_port_connection_event(port, event_type=\"down\", source=\"snmp_status\", observed_at=now, previous_status=phase79_old_status)\n                elif new_status == Port.Status.UP and phase79_old_status != Port.Status.UP:\n                    record_port_connection_event(port, event_type=\"up\", source=\"snmp_status\", observed_at=now, previous_status=phase79_old_status)\n        except Exception:\n            pass\n        updated_count += 1\n",
            1,
        )

    if "record_port_identity_snapshot(port, source=\"discovery\"" not in text:
        text = text.replace(
            "        port.save(\n            update_fields=[\n                \"neighbor_source\",\n                \"neighbor_device\",\n                \"neighbor_port\",\n                \"neighbor_ip\",\n                \"mac_count\",\n                \"mac_addresses\",\n                \"discovery_last_poll\",\n                \"updated_at\",\n            ]\n        )\n        updated_count += 1\n",
            "        port.save(\n            update_fields=[\n                \"neighbor_source\",\n                \"neighbor_device\",\n                \"neighbor_port\",\n                \"neighbor_ip\",\n                \"mac_count\",\n                \"mac_addresses\",\n                \"discovery_last_poll\",\n                \"updated_at\",\n            ]\n        )\n        try:\n            if source or macs:\n                record_port_identity_snapshot(port, source=\"discovery\", observed_at=now)\n        except Exception:\n            pass\n        updated_count += 1\n",
            1,
        )
    SNMP_TOOLS.write_text(text, encoding="utf-8")


def main():
    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    for path in (MODELS, SNMP_TOOLS, MIGRATION, HISTORY_MODULE, COMMAND):
        backup_file(path)
    patch_models()
    patch_snmp_tools()
    MIGRATION.parent.mkdir(parents=True, exist_ok=True)
    if not MIGRATION.exists():
        MIGRATION.write_text(MIGRATION_TEXT, encoding="utf-8")
    HISTORY_MODULE.write_text(HISTORY_TEXT, encoding="utf-8")
    COMMAND.parent.mkdir(parents=True, exist_ok=True)
    COMMAND.write_text(COMMAND_TEXT, encoding="utf-8")
    (ROOT / "tools" / "phase79_1_verify.py").write_text(VERIFY_TEXT, encoding="utf-8")
    print(f"PHASE79_1_PATCH_OK backup_dir={BACKUP_DIR}")


if __name__ == "__main__":
    main()
